name: Update Repository Metadata

on:
  push:
    branches: [main]
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:

jobs:
  update-metadata:
    if: github.event_name != 'push' || github.actor != 'github-actions[bot]'
    uses: Cloud2BR-TEC/.github/.github/workflows/update-repository-metadata.yml@main
    permissions:
      contents: write
    secrets: inherit